.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. regus_qt test_regus_qt
clean: FORCE
	$(MAKE) -C .. regus_qt_clean test_regus_qt_clean
check: FORCE
	$(MAKE) -C .. test_regus_qt_check
regus-qt regus-qt.exe: FORCE
	 $(MAKE) -C .. regus_qt
apk: FORCE
	$(MAKE) -C .. regus_qt_apk
